const projects = [
  {
    index: 1,
    id: "savingspree",
    title: "Savingspree",
    summary: "A web-app to track & manage your expenses.",
    description:
      "Savingspree is a webapp where you can track, analyze & manage all your expenses at one place.",
    services: ["Design", "Development"],
    builtOn: ["Nextjs", "Firebase", "ChakraUI"],
    imgSrc: "/test.png",
    imageGallery: ["/test.png", "/test.png", "/test.png"],
    siteUrl: "https://savingspree.vercel.app",
    featured: true,
  },
  {
    index: 2,
    id: "shades-generator",
    title: "Shades Generator",
    summary: "Generate different color shades.",
    services: ["Development"],
    builtOn: ["Nextjs", "ChakraUI"],
    description: "",
    imgSrc: "/test.png",
    imageGallery: ["/test.png", "/test.png", "/test.png"],
    siteUrl: "https://shades-generator.vercel.app",
  },
  {
    index: 3,
    id: "avis-tailors",
    title: "Avis Tailors",
    summary: "Custom web design & development for a tailoring brand.",
    description: "",
    services: ["Design", "Development"],
    builtOn: ["TailwindCSS", "HTML"],
    imgSrc: "/test.png",
    imageGallery: ["/test.png", "/test.png", "/test.png"],
    siteUrl: "https://avistailors.netlify.com",
  },
  {
    index: 4,
    id: "mr-lawyer",
    title: "Mr.Lawyer",
    summary: "A place where people & lawyers meet each other",
    description: "",
    services: ["Design", "Development"],
    builtOn: ["HTML", "CSS", "Javascript"],
    imgSrc: "/test.png",
    imageGallery: ["/test.png", "/test.png", "/test.png"],
    siteUrl: "https://mrlawyerfirm.web.app/",
    featured: true,
  },
];

export default projects;
